export const images = {
    p1image: require("../assets/images/p1image.png"),
    p2image: require("../assets/images/p2image.png"),
    p3image: require("../assets/images/p3image.png"),
    // arrow: require("../assets/images/arrow.png"),
    // chart: require("../assets/images/chart.png"),
    // purchase: require("../assets/images/purchase.png"),
    // order: require("../assets/images/order.png"),
    // heart: require("../assets/images/heart.png"),
    // plus: require("../assets/images/plus.png"),
    // follow: require("../assets/images/follow.png"),
    // eye: require("../assets/images/eye.png"),
    // key: require("../assets/images/key.png"),
    // inventory: require("../assets/images/inventory.png"),
    // store: require("../assets/images/store.png"),
    // message: require("../assets/images/message.png"),
    // explore: require("../assets/images/explore.png"),
    // manage: require("../assets/images/manage.png"),
    // backarrow: require("../assets/images/backarrow.png"),
    // globe: require("../assets/images/globe.png"),
    // users: require("../assets/images/users.png"),
    // phone: require("../assets/images/phone.png"),
    // cart: require("../assets/images/cart.png"),
    // bag: require("../assets/images/bag.png"),
};
